apiVersion: apps/v1
kind: Deployment
metadata:
  name: memory-app
  labels:
    app: memory-app
spec:
  selector:
    matchLabels:
      app: memory-app
  template:
    metadata:
      labels:
        app: memory-app
    spec:
      containers:
      - name: memory-app
        image: nginx
        resources:
          requests:
            memory: 128Mi
          limits:
            memory: 256Mi
        ports:
        - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: memory-app-service
spec:
  selector:
    app: memory-app
  ports:
  - port: 80
    targetPort: 80
  type: ClusterIP

---

apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: memory-app-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: memory-app
  minReplicas: 2
  maxReplicas: 8
  metrics:
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 60
